### ISSUE TITLE
0.11.10 won't compile

### ISSUE THREAD

**Issue by frdoni** [jyberg/Enhanced-Nextion-Library#15]
Hi,

I've discovered that:

a semicolon is missing in NexObject.hm at the end of line 75, so line must be: bool setVisible(bool visible);
a semicolon is missing in Nexpage.hm at the end of line 53, so line must be: bool setVisible(bool visible);

in nexPage.cpp, at line 43 "flag" variable must be "visible", because flag is not declared
in nexObject.cpp, at line 112 "flag" variable must be "visible", because flag is not declared

Francesco

**Comment by jyberg** [comment]
I managed to change the code via phone.. shoud be corrected now...
