### ISSUE TITLE
Wiring question

### ISSUE THREAD

**Issue by fondberg** [jyberg/Enhanced-Nextion-Library#17]
Firstly,  great work!
Do you know the wiring for these displays? My K nextion doesnt have any printed labels on the 40pins it has.

**Comment by jyberg** [comment]
hmmm, do you have Intelligent or Enhanced display they had in back in other end extension connector and in othe end TX,RX,+5v,GND connector. You need to connect power on +5 and GND. UPS to Serial converter or power from Arduino or ESP/NodeMCU board not give enouhg power so if connecting to USP for probramming connect bard with other cable and Display with other USB cable+adapter.  then Display RX to board TX and Display TX to board RX.  
 see https://nextion.tech/intelligent-series-introduction/  in the end of page it has picture and left side is the power / RXTX connector. Also in following page https://nextion.tech/intelligent-series-introduction/ there is table and in the table row Pictures you see power and TXRX connector cable that should come with display

**Comment by fondberg** [comment]
Thanks
