### ISSUE TITLE
currentPageIdCallback usage

### ISSUE THREAD

**Issue by pilaf78** [jyberg/Enhanced-Nextion-Library#21]
Hi ,

First off all , thank you for this awesome library :)

Now im blocked on an implementation of the currentPageIdCallback 
I have no idea how to implement that...
Should i give a pointer of function ? 

Can you give me an exemple of implementation ?

Many thanks for you help

**Comment by jyberg** [comment]
hi,
- first initialize the nextion instance:
SoftwareSerial nexSerial(D2, D1); // RX, TX
Nextion *nextion = Nextion::GetInstance(nexSerial);

-CurrentPageId is callback function that you need initialize:
	// functional callbacks
	nextion->currentPageIdCallback = currentPageCallback;

- And callback function definition e.g...
void currentPageCallback(uint8_t pageId)
{
	if(currentPageId==pageId)
	{
		return;
	}
	currentPageId=pageId;
}

**Comment by pilaf78** [comment]
Good its ok
Many thanks :)
