### ISSUE TITLE
Info about which Nextion editor that is supported.

### ISSUE THREAD

**Issue by kreativum2021** [jyberg/Enhanced-Nextion-Library#24]
Hi
If you read the info about different versions of the Nextion HMI editor, then the LTE (0.53) version is not compatible with the newest version when it comes to the original library. Would be nice to have some info about which versions of the Nextion HMI editor this library supports.
Thx Fredrik

**Comment by jyberg** [comment]
hi, library works over serial communication port,.and is such not depend from Nextion editor version. Library uses serial commands documented in https://nextion.tech/instruction-set/ I have not noticed that base components interfaces  has changed. I have not implemented support for latest itelligent componens as I don't have intelligent device available.
