### ISSUE TITLE
Outdated library.json and library.properties?

### ISSUE THREAD

**Issue by maxus-git** [jyberg/Enhanced-Nextion-Library#29]
Hi,

I didn't receive updates in platformio.
Can it be that the <<library.json>> and <<library.properties>> are outdated?
library.json --> "version": "1.2.3"
library.properties --> version=1.2.0

![enh-next-platformio-outdated](https://user-images.githubusercontent.com/67929621/161708768-d169cc82-dc62-4365-8e2b-c28a505d4f00.png)

Thank you,
Markus

**Comment by jyberg** [comment]
yes,
you are correct I have forgot to update it to platformio, I will try to do it on next weekend....

thanks,
Jyrki

**Comment by jyberg** [comment]
Latest version now available in platformio registry
