### ISSUE TITLE
Update version in "library.json" and "library.properties"

### ISSUE THREAD

**Issue by maxus-git** [jyberg/Enhanced-Nextion-Library#36]
Hi Jyrki,

can you please update also the `library.json` and `library.properties` to version 1.5.0 (still on 1.4.3) so that the library can be updated also in Platform.IO?

Thank you!

Best regards,
Markus

**Comment by jyberg** [comment]
Thanks, vesion not updated to 1.5.1 it should be available on Platform.IO after some time...

**Comment by maxus-git** [comment]
Hi Jyrki,

PlatformIO still shows the last version with 1.4.3 --> The registry at "https://registry.platformio.org/libraries/jyberg/Enhanced-Nextion-Library" is not up to date with Github.

**Comment by jyberg** [comment]
I did again re-publish now it looks like it is finally updated on platformio...

**Comment by maxus-git** [comment]
Hi Jyrki,
thank you - looks good now.
