### ISSUE TITLE
ESP32 WROOM-32U 

### ISSUE THREAD

**Issue by Gaab88** [jyberg/Enhanced-Nextion-Library#37]
Hello!

 Is your library compatible with the controller mentioned above?

If so, fully?

Regards

**Comment by jyberg** [comment]
library uses atandard c++ so I don't see any reason why it is not capatible. nextion dispaly is controllednover hw or sw io dependin on your usage/project settings.
I don't have this development board but I have had any issues with aby esp32 versions that I have used...
