### ISSUE TITLE
esp32 dev kit-v1

### ISSUE THREAD

**Issue by MatheusCaltran** [jyberg/Enhanced-Nextion-Library#38]
Good afternoon, have you tested this library with the esp32 dev kit-v1?

I'm using the Nextion Intelligent 7 with this ESP in the official library but I'm suffering a bit. I would like to test yours but I can't communicate between the ESP and the Nextion (I tried with the HW and without it too) it always shows "nextion init fails"

**Comment by jyberg** [comment]
hi,
I don't have that ESP board, but if you get connection with "official" library I don't see that there should be problems as communication method is same. What I have noted that official library was not maintained at all, and it had huge amount of bugs, and that why I created this...
