### ISSUE TITLE
Serial linking

### ISSUE THREAD

**Issue by burnt-past** [jyberg/Enhanced-Nextion-Library#5]
Hey jyberg,

I am using another function that uses the serial port 0 and 1.

It seems that the Enhanced library is using the USART0_RX_recv vector(25).

This is the error I am getting: (.text+0x0) multiple definition of __vector_25
I am already using this serial line in another function and I am not recalling it in the config.h

I can't find where it is using it but I am unable to compile because of this. Everything works fine with the iTead library, at least as well as it can.

I'm probably missing something. Let me know what you think!

**Comment by jyberg** [comment]
nextion library has no __vector_25 definition so I it looks like not problem in nextion library
