### ISSUE TITLE
SoftwareSerial include in NexUpload.cpp

### ISSUE THREAD

**Issue by tomtobback** [jyberg/Enhanced-Nextion-Library#7]
I'm working with a SAMD board and the library does not compile because it tries to include SoftwareSerial.h in https://github.com/jyberg/Enhanced-Nextion-Library/blob/master/NexUpload.cpp even if `USE_SOFTWARE_SERIAL` is undefined. Please move that line into the `#ifdef USE_SOFTWARE_SERIAL` block, same as in https://github.com/jyberg/Enhanced-Nextion-Library/blob/master/NexHardware.cpp
With this change, the library compiles for my board.

**Comment by jyberg** [comment]
Change done
